### PR TITLE
Add some unit tests to get started

### PR DESCRIPTION
**Pull request by plars**
Add some unit tests for testflinger-cli. Far from good coverage, but it's a start

### CODE REVIEW

**Comment by jocave** [comment]
Looks like the pycache got added and should be removed.

Can we get the unittests to run even on this PR?

**Review by jocave — CHANGES_REQUESTED** [review]
Remove pycache

**Comment by plars** [comment]
> Remove pycache

Ok, sorry for the force push but I didn't want the binary files in the history. I've pushed one without them now. I really thought I had a .gitignore in this project but looks like I need to add one of those too :)

**Review by jocave — APPROVED** [review]
Ok looks better now, thanks

**Pull request merged**
